### ISSUE TITLE
Making maps from open-source code and open datasets

### ISSUE THREAD

**Issue by rmglennon** [OpenSourceShowAndTell/SanFrancisco2017#9]
I'm willing to do a talk about the open-source initiatives at [Mapzen](https://mapzen.com/). 

Mapzen makes tools for developers to integrate maps, turn-by-turn navigation, and geographic search into their mobile and web apps. All the code is open-source (usually MIT-licensed), and the data used is also openly licensed.

Presenter: Rhonda Glennon, Mapzen, https://github.com/rmglennon

PS - This doesn't need to be 10 minutes; I can do it in a shorter lightning-style format, too.

**Comment by elof** [comment]
Hey @rmglennon we are a little oversubscribed on talks right now, but if you come and we end up having extra time I'm happy to let you give your talk. We are usually able to give everyone an opportunity

**Comment by rmglennon** [comment]
Sounds good, @elof. I'm here, and it's fine if we are too tight on time. Thanks for organizing!
